/**
 * Copyright 2021 Huawei Technologies Co., Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace mindspore {
namespace lite {
#ifdef MS_COMPILE_IOS
// populate
extern void _PrimitiveType_Mul();
extern void _PrimitiveType_NonMaxSuppression();
extern void _PrimitiveType_TensorListStack();
extern void _PrimitiveType_Eltwise();
extern void _PrimitiveType_Assign();
extern void _PrimitiveType_Crop();
extern void _PrimitiveType_BatchNorm();
extern void _PrimitiveType_NonZero();
extern void _PrimitiveType_AddN();
extern void _PrimitiveType_Merge();
extern void _PrimitiveType_Abs();
extern void _PrimitiveType_Cos();
extern void _PrimitiveType_Sin();
extern void _PrimitiveType_Log();
extern void _PrimitiveType_Neg();
extern void _PrimitiveType_NegGrad();
extern void _PrimitiveType_LogGrad();
extern void _PrimitiveType_AbsGrad();
extern void _PrimitiveType_Sqrt();
extern void _PrimitiveType_Square();
extern void _PrimitiveType_Rsqrt();
extern void _PrimitiveType_LogicalNot();
extern void _PrimitiveType_Floor();
extern void _PrimitiveType_Ceil();
extern void _PrimitiveType_Round();
extern void _PrimitiveType_Reciprocal();
extern void _PrimitiveType_Erf();
extern void _PrimitiveType_AssignAdd();
extern void _PrimitiveType_Unique();
extern void _PrimitiveType_Tile();
extern void _PrimitiveType_Upsample();
extern void _PrimitiveType_BinaryCrossEntropyGrad();
extern void _PrimitiveType_StridedSlice();
extern void _PrimitiveType_L2Norm();
extern void _PrimitiveType_Range();
extern void _PrimitiveType_CropAndResize();
extern void _PrimitiveType_QuantDTypeCast();
extern void _PrimitiveType_InstanceNorm();
extern void _PrimitiveType_Add();
extern void _PrimitiveType_DeDepthwiseConv2D();
extern void _PrimitiveType_DeConv2D();
extern void _PrimitiveType_Power();
extern void _PrimitiveType_Reverse();
extern void _PrimitiveType_BiasAdd();
extern void _PrimitiveType_TensorListReserve();
extern void _PrimitiveType_MatMul();
extern void _PrimitiveType_RealDiv();
extern void _PrimitiveType_LogicalAnd();
extern void _PrimitiveType_LogicalOr();
extern void _PrimitiveType_Equal();
extern void _PrimitiveType_NotEqual();
extern void _PrimitiveType_Less();
extern void _PrimitiveType_LessEqual();
extern void _PrimitiveType_Greater();
extern void _PrimitiveType_GreaterEqual();
extern void _PrimitiveType_Maximum();
extern void _PrimitiveType_Minimum();
extern void _PrimitiveType_FloorDiv();
extern void _PrimitiveType_FloorMod();
extern void _PrimitiveType_Mod();
extern void _PrimitiveType_SquaredDifference();
extern void _PrimitiveType_OneHot();
extern void _PrimitiveType_While();
extern void _PrimitiveType_ScatterND();
extern void _PrimitiveType_DepthwiseConv2D();
extern void _PrimitiveType_DepthToSpace();
extern void _PrimitiveType_Nhwc2Nchw();
extern void _PrimitiveType_Gather();
extern void _PrimitiveType_Assert();
extern void _PrimitiveType_OnesLike();
extern void _PrimitiveType_Concat();
extern void _PrimitiveType_Scale();
extern void _PrimitiveType_HashtableLookup();
extern void _PrimitiveType_Stack();
extern void _PrimitiveType_Shape();
extern void _PrimitiveType_SparseToDense();
extern void _PrimitiveType_TensorListFromTensor();
extern void _PrimitiveType_ReverseSequence();
extern void _PrimitiveType_Unsqueeze();
extern void _PrimitiveType_Flatten();
extern void _PrimitiveType_ArgMin();
extern void _PrimitiveType_SpaceToBatch();
extern void _PrimitiveType_Unstack();
extern void _PrimitiveType_BroadcastTo();
extern void _PrimitiveType_Select();
extern void _PrimitiveType_BiasGrad();
extern void _PrimitiveType_LayerNorm();
extern void _PrimitiveType_EmbeddingLookup();
extern void _PrimitiveType_CustomExtractFeatures();
extern void _PrimitiveType_Resize();
extern void _PrimitiveType_Adam();
extern void _PrimitiveType_ExpandDims();
extern void _PrimitiveType_SoftMax();
extern void _PrimitiveType_BatchToSpace();
extern void _PrimitiveType_BatchToSpaceND();
extern void _PrimitiveType_UniformReal();
extern void _PrimitiveType_DetectionPostProcess();
extern void _PrimitiveType_GatherNd();
extern void _PrimitiveType_Gru();
extern void _PrimitiveType_CustomNormalize();
extern void _PrimitiveType_Adder();
extern void _PrimitiveType_RandomStandardNormal();
extern void _PrimitiveType_FusedBatchNorm();
extern void _PrimitiveType_Pooling();
extern void _PrimitiveType_ArgMax();
extern void _PrimitiveType_Exp();
extern void _PrimitiveType_SpaceToBatchND();
extern void _PrimitiveType_ROIPooling();
extern void _PrimitiveType_PReLU();
extern void _PrimitiveType_Where();
extern void _PrimitiveType_Partial();
extern void _PrimitiveType_Sub();
extern void _PrimitiveType_Div();
extern void _PrimitiveType_Split();
extern void _PrimitiveType_Activation();
extern void _PrimitiveType_TopK();
extern void _PrimitiveType_Cast();
extern void _PrimitiveType_Slice();
extern void _PrimitiveType_Transpose();
extern void _PrimitiveType_Reduce();
extern void _PrimitiveType_Nchw2Nhwc();
extern void _PrimitiveType_FullConnection();
extern void _PrimitiveType_LshProjection();
extern void _PrimitiveType_SkipGram();
extern void _PrimitiveType_Squeeze();
extern void _PrimitiveType_ActivationGrad();
extern void _PrimitiveType_Switch();
extern void _PrimitiveType_Lstm();
extern void _PrimitiveType_BinaryCrossEntropy();
extern void _PrimitiveType_Elu();
extern void _PrimitiveType_Conv2D();
extern void _PrimitiveType_TensorListGetItem();
extern void _PrimitiveType_LocalResponseNormalization();
extern void _PrimitiveType_Reshape();
extern void _PrimitiveType_ConstantOfShape();
extern void _PrimitiveType_CustomPredict();
extern void _PrimitiveType_Pad();
extern void _PrimitiveType_PriorBox();
extern void _PrimitiveType_ZerosLike();
extern void _PrimitiveType_Size();
extern void _PrimitiveType_InvertPermutation();
extern void _PrimitiveType_UnsortedSegmentSum();
extern void _PrimitiveType_TensorListSetItem();
extern void _PrimitiveType_Fill();
extern void _PrimitiveType_SpaceToDepth();

void RegisterOps() {
  _PrimitiveType_Mul();
  _PrimitiveType_NonMaxSuppression();
  _PrimitiveType_TensorListStack();
  _PrimitiveType_Eltwise();
  _PrimitiveType_Assign();
  _PrimitiveType_Crop();
  _PrimitiveType_BatchNorm();
  _PrimitiveType_NonZero();
  _PrimitiveType_AddN();
  _PrimitiveType_Merge();
  _PrimitiveType_Abs();
  _PrimitiveType_Cos();
  _PrimitiveType_Sin();
  _PrimitiveType_Log();
  _PrimitiveType_Neg();
  _PrimitiveType_NegGrad();
  _PrimitiveType_LogGrad();
  _PrimitiveType_AbsGrad();
  _PrimitiveType_Sqrt();
  _PrimitiveType_Square();
  _PrimitiveType_Rsqrt();
  _PrimitiveType_LogicalNot();
  _PrimitiveType_Floor();
  _PrimitiveType_Ceil();
  _PrimitiveType_Round();
  _PrimitiveType_Reciprocal();
  _PrimitiveType_Erf();
  _PrimitiveType_AssignAdd();
  _PrimitiveType_Unique();
  _PrimitiveType_Tile();
  _PrimitiveType_Upsample();
  _PrimitiveType_BinaryCrossEntropyGrad();
  _PrimitiveType_StridedSlice();
  _PrimitiveType_L2Norm();
  _PrimitiveType_Range();
  _PrimitiveType_CropAndResize();
  _PrimitiveType_QuantDTypeCast();
  _PrimitiveType_InstanceNorm();
  _PrimitiveType_Add();
  _PrimitiveType_DeDepthwiseConv2D();
  _PrimitiveType_DeConv2D();
  _PrimitiveType_Power();
  _PrimitiveType_Reverse();
  _PrimitiveType_BiasAdd();
  _PrimitiveType_TensorListReserve();
  _PrimitiveType_MatMul();
  _PrimitiveType_RealDiv();
  _PrimitiveType_LogicalAnd();
  _PrimitiveType_LogicalOr();
  _PrimitiveType_Equal();
  _PrimitiveType_NotEqual();
  _PrimitiveType_Less();
  _PrimitiveType_LessEqual();
  _PrimitiveType_Greater();
  _PrimitiveType_GreaterEqual();
  _PrimitiveType_Maximum();
  _PrimitiveType_Minimum();
  _PrimitiveType_FloorDiv();
  _PrimitiveType_FloorMod();
  _PrimitiveType_Mod();
  _PrimitiveType_SquaredDifference();
  _PrimitiveType_OneHot();
  _PrimitiveType_While();
  _PrimitiveType_ScatterND();
  _PrimitiveType_DepthwiseConv2D();
  _PrimitiveType_DepthToSpace();
  _PrimitiveType_Nhwc2Nchw();
  _PrimitiveType_Gather();
  _PrimitiveType_Assert();
  _PrimitiveType_OnesLike();
  _PrimitiveType_Concat();
  _PrimitiveType_Scale();
  _PrimitiveType_HashtableLookup();
  _PrimitiveType_Stack();
  _PrimitiveType_Shape();
  _PrimitiveType_SparseToDense();
  _PrimitiveType_TensorListFromTensor();
  _PrimitiveType_ReverseSequence();
  _PrimitiveType_Unsqueeze();
  _PrimitiveType_Flatten();
  _PrimitiveType_ArgMin();
  _PrimitiveType_SpaceToBatch();
  _PrimitiveType_Unstack();
  _PrimitiveType_BroadcastTo();
  _PrimitiveType_Select();
  _PrimitiveType_BiasGrad();
  _PrimitiveType_LayerNorm();
  _PrimitiveType_EmbeddingLookup();
  _PrimitiveType_CustomExtractFeatures();
  _PrimitiveType_Resize();
  _PrimitiveType_Adam();
  _PrimitiveType_ExpandDims();
  _PrimitiveType_SoftMax();
  _PrimitiveType_BatchToSpace();
  _PrimitiveType_BatchToSpaceND();
  _PrimitiveType_UniformReal();
  _PrimitiveType_DetectionPostProcess();
  _PrimitiveType_GatherNd();
  _PrimitiveType_Gru();
  _PrimitiveType_CustomNormalize();
  _PrimitiveType_Adder();
  _PrimitiveType_RandomStandardNormal();
  _PrimitiveType_FusedBatchNorm();
  _PrimitiveType_Pooling();
  _PrimitiveType_ArgMax();
  _PrimitiveType_Exp();
  _PrimitiveType_SpaceToBatchND();
  _PrimitiveType_ROIPooling();
  _PrimitiveType_PReLU();
  _PrimitiveType_Where();
  _PrimitiveType_Partial();
  _PrimitiveType_Sub();
  _PrimitiveType_Div();
  _PrimitiveType_Split();
  _PrimitiveType_Activation();
  _PrimitiveType_TopK();
  _PrimitiveType_Cast();
  _PrimitiveType_Slice();
  _PrimitiveType_Transpose();
  _PrimitiveType_Reduce();
  _PrimitiveType_Nchw2Nhwc();
  _PrimitiveType_FullConnection();
  _PrimitiveType_LshProjection();
  _PrimitiveType_SkipGram();
  _PrimitiveType_Squeeze();
  _PrimitiveType_ActivationGrad();
  _PrimitiveType_Switch();
  _PrimitiveType_Lstm();
  _PrimitiveType_BinaryCrossEntropy();
  _PrimitiveType_Elu();
  _PrimitiveType_Conv2D();
  _PrimitiveType_TensorListGetItem();
  _PrimitiveType_LocalResponseNormalization();
  _PrimitiveType_Reshape();
  _PrimitiveType_ConstantOfShape();
  _PrimitiveType_CustomPredict();
  _PrimitiveType_Pad();
  _PrimitiveType_PriorBox();
  _PrimitiveType_ZerosLike();
  _PrimitiveType_Size();
  _PrimitiveType_InvertPermutation();
  _PrimitiveType_UnsortedSegmentSum();
  _PrimitiveType_TensorListSetItem();
  _PrimitiveType_Fill();
  _PrimitiveType_SpaceToDepth();
}

#endif
}  // namespace lite
}  // namespace mindspore
